"""
====================================================
AI HEALTH GUARDIAN
AI Analysis Component
Final Version
====================================================
"""

import streamlit as st


# ======================================================
# Medical Analysis Section
# ======================================================

def show_analysis(
    medical_reasoning,
    lifestyle,
    reminders
):
    """
    Displays all AI generated outputs in a
    professional dashboard.
    """

    st.header("🧠 AI Health Analysis")

    st.markdown(
        "Powered by **IBM watsonx.ai** using **Meta Llama 3.3 70B**"
    )

    st.markdown("---")

    # ==========================================
    # TABS
    # ==========================================

    tab1, tab2, tab3 = st.tabs([
        "🩺 Medical Reasoning",
        "🥗 Lifestyle Plan",
        "⏰ Daily Reminders"
    ])

    # ==========================================
    # MEDICAL REASONING
    # ==========================================

    with tab1:

        st.subheader("🧠 AI Medical Reasoning")

        st.info(
            """
The following explanation has been generated
using IBM watsonx.ai after analyzing the
patient's health information.
"""
        )

        with st.expander(
            "📖 View Complete Medical Analysis",
            expanded=True
        ):

            st.markdown(medical_reasoning)

    # ==========================================
    # LIFESTYLE PLAN
    # ==========================================

    with tab2:

        st.subheader("🥗 Personalized Lifestyle Plan")

        st.success(
            """
Your personalized lifestyle recommendations
generated by the AI model.
"""
        )

        with st.expander(
            "💪 Healthy Lifestyle Recommendations",
            expanded=True
        ):

            st.markdown(lifestyle)

    # ==========================================
    # REMINDERS
    # ==========================================

    with tab3:

        st.subheader("⏰ Daily Health Reminders")

        st.warning(
            "Follow these reminders every day."
        )

        for reminder in reminders:

            st.checkbox(
                reminder,
                value=False
            )

    st.markdown("---")

    # ==========================================
    # AI INSIGHTS
    # ==========================================

    st.subheader("🤖 AI Insights")

    c1, c2, c3 = st.columns(3)

    with c1:

        st.success(
            """
### 🍎 Diet

Eat vegetables

Reduce sugar

Drink water
"""
        )

    with c2:

        st.info(
            """
### 🏃 Exercise

Walk 30 mins

Light cardio

Stretch daily
"""
        )

    with c3:

        st.warning(
            """
### 😴 Sleep

7–8 hours

Reduce stress

Sleep early
"""
        )

    st.markdown("---")

    # ==========================================
    # NEXT STEPS
    # ==========================================

    st.subheader("✅ Recommended Next Steps")

    st.write("✔ Consult a physician if symptoms persist.")

    st.write("✔ Continue regular health monitoring.")

    st.write("✔ Maintain a healthy diet.")

    st.write("✔ Exercise consistently.")

    st.write("✔ Repeat health screening every 6–12 months.")

    st.markdown("---")

    # ==========================================
    # DISCLAIMER
    # ==========================================

    st.warning(
        """
### ⚠ Medical Disclaimer

This AI-generated report is intended for
educational and decision-support purposes.

It is **NOT** a replacement for professional
medical advice.

Always consult a qualified healthcare
professional before making any medical
decisions.
"""
    )